### ISSUE TITLE
vaadin-date-picker UI design

### ISSUE THREAD

**Issue by jounik** [vaadin/vaadin-components#3]
A component for selecting a date or multiple dates/a range of dates.

#### 1.0

* Select a single date
* Date input by pointer and/or keyboard
 * Textual input
 * Calendar picker, with quick access to all months and years
   * Optional week numbers
    * Start week from Sunday or Monday
* Basic accessibility (focus handling and keyboard navigation)
* Localization (a way to replace all texts in the picker UI)
 * Provide one language (English) by default

#### 1.1

* Customizable theme (cross-scope styling support)

#### 1.2

* Improved accessibility (WAI-ARIA) support

#### 1.3

* Disabled/disallowed dates

#### 1.4

* Select multiple dates or date ranges: displayed as tokens in the input field

### UI Design

- [x] End user feature design: features for 1.0 and a few minor further
- Prototype selected designs or parts of a design 
 - [x] [Implementation](https://github.com/vaadin/components-team-tasks/issues/8)
 - [x] [User testing](https://github.com/vaadin/components-team-tasks/issues/9)

### Attachments (prior ideation)

- [Prototype](http://jouni.me/upload/date-picker/demo.html)
- [Touch interface mockup](https://drive.google.com/a/vaadin.com/file/d/0BzNRYMf7bO7kN0UyYWd0bDRURWM/view)
- [Desktop mockup](https://drive.google.com/a/vaadin.com/file/d/0BzNRYMf7bO7kLUNiYWo3SUZBRXc/view)

**Comment by cwayfinder** [comment]
Probably you can borrow ideas from this http://www.materialup.com/collections/calendars-in-material-design

**Comment by tuomasnironen** [comment]
Should the suggested element name be `vaadin-datepicker`? You see both versions used but with a quick googling "datepicker" appears to be written as one word in top search results.

**Comment by tuomasnironen** [comment]
Should the element include also time picker or just the dates for now? Ping @jounik

**Comment by jounik** [comment]
Just dates now.

**Comment by jounik** [comment]
Forgot to comment about the element name. That’s not really that important right now, but I would personally go with `vaadin-date-picker` since the correct English wording is “date picker” (even though many widgets still use “datepicker”).

**Comment by tuomasnironen** [comment]
Attaching an initial version (for mobile screens) with some variations in the UI. Please take a look and let me know your likes/dislikes/other comments @jounik .

![iphone 6 2x - date picker](https://cloud.githubusercontent.com/assets/13781525/9905269/b34570ee-5c8c-11e5-8b1b-e9d1a46a5ad4.png)

**Comment by Saulis** [comment]
:trophy:

**Comment by tuomasnironen** [comment]
Latest iterations of UI layout here:
![iphone 6 2x - date picker](https://cloud.githubusercontent.com/assets/13781525/9956781/0a093f78-5e04-11e5-8a35-efb910213dd9.png)
![desktop hd - date picker](https://cloud.githubusercontent.com/assets/13781525/9956782/0a2295f4-5e04-11e5-8b62-c6a10a711b27.png)

**Comment by jounik** [comment]
For inspiration, here’s the same component from Angular Material: https://material.angularjs.org/latest/#/demo/material.components.datepicker

**Comment by jounik** [comment]
Some questions that came up when looking at the designs:

- How does keyboard navigation work inside the popups?
- How do you move between the month and year lists in the infinite scrollable popup?
- What are the “…” in the month list?
- Does the large screen popup always open centered on the screen, or where?

Intuitively I would prefer the infinite scrolling list, with the option for toggling the granularity from days to months to years (i.e. show the full day calendars or only a list of month names or a list of year numbers in the scrolling list).

**Comment by tuomasnironen** [comment]
# Scope 1.0 requirements

* select a single date
* select a date range (begin and end date, double datepickers)
* "drill" navigation between days < - > months < - > years
* localization by different languages (in English by default)
* pointer and keyboard navigation
* no calendar icon by default

# Next important features

* select multiple dates or date ranges: displayed as tokens in input field
* input day/month/year directly in separate input fields
* disabled dates
* customizable datepicker icon
* scrollable infinite calendar view

**Comment by tuomasnironen** [comment]
### Use case scenarios for design and usability testing

1. You are viewing TV shows for the weekend. Select next Sunday using the date picker.
2. You are signing up as a new customer in a web shop. Input your birthday in the relevant field in the registration form. Use your desktop browser to input this date in the relevant input field.
3. You are searching for available rooms in a hotel during your visit 28th December 2015 - 2nd January 2016. Use your mobile device to input this date range in the relevant date field on the search form.

**Comment by jounik** [comment]
Moved the feature list to the main description, and copied the use case descriptions into a Google Doc.

**Comment by jounik** [comment]
Idea for the month/year navigation. Both infinite list views, the other one has a “shortcut” sidebar to quickly jump to a certain year (similar to iOS contacts list alphabet links):
![date-picker-year-month-navigation](https://cloud.githubusercontent.com/assets/66382/10094244/0aa8f9f2-6366-11e5-8cc3-9498ec56e0dd.png)

**Comment by tuomasnironen** [comment]
Good ideas. I will include them in the next design iteration. In the meantime, here is the updated UI layout for what I was working on:
![iphone 6 2x - date picker](https://cloud.githubusercontent.com/assets/13781525/10095682/3dade138-6374-11e5-8993-55f911e99fd9.png)

**Comment by tuomasnironen** [comment]
Graphical design status update: The designs include patterns for 1.0 features. Later version features will be added in the future design updates, as well as 1.0 designs will be revised according to feedback from proto user testing.
